name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
    steps:
      - uses: Agile-visualizer-Team/TestRepo/.github/workflows/workflow-B.yml@develop
        with:
          config-path: .github/labeler.yml
          test: "CIAO"
          token: ${{ secrets.GITHUB_TOKEN }}