run-name: Checking if ${{ github.actor }} wants to create a pull_request :)
name: Check for pull request commit
on:
  workflow_dispatch:
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0