run-name: Workflow 2 is running
name: Workflow 2
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
      reviewer:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - run: echo "${{ input.title }}"
      - run: echo "${{ secrets.token }}"
    